name: dept_to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.0
  firebase_cloud_firestore: ^5.4.4
  
  flutter:
    sdk: flutter
  intl: ^0.19.0
  line_icons: ^2.0.3
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  cool_nav: ^0.1.1
  flutter_svg: ^2.0.17
  toasty_box: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
